### ISSUE TITLE
Search Bar: Allows User Input, pulls up house location.

### ISSUE THREAD

**Issue by Zoocko42** [Zoocko42/skrongproject1#3]
**Search Bar Input:**

Specific Address

**Search Bar Output:** 

Nearby Attractions/Services based on the checkbox Parameters

**Search Bar Includes:**

1. Distance Parameter
- Within 1-50 Miles (Slider)
- Tickbox for every 10 miles.
2. Number of Results 
3. Checkbox Parameters- Parks
- Bodies of Water
- Restaurants
- Groceries
- Entertainment (Theaters, mini-golf, badminton, curling rinks)
- Bars/Breweries 

**Save Recent Searches**
For user-friendliness (and to satisfy project requirements) the user should be able to save/retrive recent search results.

**Comment by a1exlin** [comment]
Search bar along with a Nav bar has been created using bootstrap link

**Comment by a1exlin** [comment]
Search box result completely made. However, it needs corrections
